config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :only => [:index, :show, :update,:destroy]

  resources :microposts, :only => [:create, :destroy, :show] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  root 'static_pages#home'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :micropost
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, micropost_id: params[:micropost_id])
    @likes = Like.where(micropost_id: params[:micropost_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, micropost_id: params[:micropost_id])
    like.destroy
    @likes = Like.where(micropost_id: params[:micropost_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if micropost.like_user(current_user.id) %>
  <%= link_to micropost_like_path(likes, micropost_id: micropost.id), method: :delete, id: "like-button", remote: true do %>
    <%= image_tag("icon_red_heart.png") %>
  <% end %>
<% else %>
  <%= link_to micropost_likes_path(micropost),method: :post, id: "like-button", remote: true do %>
    <%= image_tag("icon_heart.png") %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { micropost: micropost, likes: @likes, like: @like}) %>");

app/views/likes/destroy.js.erb
$("#like-button").html("<%= j(render partial: 'like', locals: { micropost: micropost, likes: @likes }) %>");