config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :only => [:index, :show, :update,:destroy]

  resources :microposts, :only => [:create, :destroy, :show] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  root 'static_pages#home'
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy

  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end

  private

   def picture_size
     if picture.size > 5.megabytes
       errors.add(:picture, "should be less than 5MB")
     end
   end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  before_action :correct_user,   only: [:destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to request.referrer || root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :picture, :user_id)
  end

  def correct_user
    @micropost = current_user.microposts.find_by!(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
      <% if current_user == micropost.user %>
        <%= link_to "delete", micropost, method: :delete,
                                         data: { confirm: "本当に削除しますか？" } %>
        <%= link_to "コメントする", new_micropost_comment_path(micropost) %>
      <% end %>
    </span>

    <span>
      <% micropost.comments.each do |comment| %>
        <%= comment.user.name %>
        <%= comment.content %>
        <%= link_to "編集する", edit_micropost_comment_path(micropost, comment) %>
      <% end %>
  </span>
  </li>

app/views/microposts/_micropost.html.haml
%li{:id => "micropost-#{micropost.id}"}
  = link_to gravatar_for(micropost.user, size: 50), micropost.user
  %span.user= link_to micropost.user.name, micropost.user
  %span.content
    = micropost.content
    = image_tag micropost.picture.url if micropost.picture?
  %span.timestamp
    Posted #{time_ago_in_words(micropost.created_at)} ago.
    - if current_user == micropost.user
      = link_to "削除する", micropost, method: :delete, |
        data: { confirm: "本当に削除しますか？" }             |
      = link_to "コメントする", new_micropost_comment_path(micropost)
      - if micropost.comments.present?
        = link_to "コメント(#{micropost.comments.count})", micropost_comments_path(micropost)
      = render partial: 'likes/like', locals: { micropost: micropost, likes: @likes }