config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :only => [:index, :show, :update,:destroy]

  resources :microposts, :only => [:create, :destroy, :show] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :micropost
  belongs_to :user
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy

  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end

  private

   def picture_size
     if picture.size > 5.megabytes
       errors.add(:picture, "should be less than 5MB")
     end
   end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :microposts, dependent: :destroy
  validates :name, presence: {message: 'を入力してください'}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

def feed
  Micropost.where("user_id = ?", id)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  protect_from_forgery with: :exception


  def hello
    render html: "Hello,world!"
  end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :name)}

    devise_parameter_sanitizer.permit(:sign_in){|u| u.permit(:user_id, :password, :remember_me)}
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_micropost, only: [:new,:edit,:create,:update,:destroy]
  before_action :set_comment, only: [:edit,:update,:destroy]

  def new
    @comment = @micropost.comments.build
  end


  def edit
  end

  def create
    @comment = @micropost.comments.build(user_id: current_user.id,
                                         content: comment_params[:content])
    if @comment.save
      redirect_to root_url
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to root_url
    else
      render :edit
    end
  end

  def destroy
   @comment.destroy!
   redirect_to root_url
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :micropost_id)
  end

  def set_micropost
    @micropost = Micropost.find(params[:micropost_id])
  end

  def set_comment
    @comment = @micropost.comments.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, micropost_id: params[:micropost_id])
    @likes = Like.where(micropost_id: params[:micropost_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, micropost_id: params[:micropost_id])
    like.destroy
    @likes = Like.where(micropost_id: params[:micropost_id])
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  before_action :correct_user,   only: [:destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to request.referrer || root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :picture, :user_id)
  end

  def correct_user
    @micropost = current_user.microposts.find_by!(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  skip_before_action :authenticate_user!, only:[:home,:help,:about,:contact]

  def home
    if user_signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @likes = Like.where(micropost_id: params[:micropost_id])
    end
  end

  def help
  end

  def About
  end

  def contact
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_correct_user, only:[:edit,:update,:show]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find_by!(id: params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    @likes = Like.where(micropost_id: params[:micropost_id])
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find!(params[:id]).destroy
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def ensure_correct_user
    if current_user.id != params[:id].to_i
      redirect_to(root_url)
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    %a{ :href => 'https://railstutorial.jp/'}
    Ruby on Rails Tutorial
    by
    %a{ :href => 'http://www.michaelhartl.com/'}
    Michael Hartl
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li<
        %a{ :href => "http://news.railstutorial.org/"} News

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "sample app", root_path, id: "logo"
      %nav
        %ul.nav.nav-pills.navbar-right
          - if user_signed_in?
            %li.nav-item= link_to "Home",   root_path
            %li= link_to "Help",   help_path
            %li= link_to "マイページ", user_path(current_user)
            %li= link_to "ユーザーリスト", users_path
            %li= link_to 'ログアウト', destroy_user_session_path, method: :delete
          - else
            %li= link_to "Home",   root_path
            %li= link_to "Help",   help_path
            %li= link_to '会員登録', new_user_registration_path
            %li= link_to 'ログイン', new_user_session_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
%head
  %title
    = full_title(yield(:title))
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = render 'layouts/shim'
%body
  = render "layouts/flash"
  = render "layouts/header"
%div.container
  = yield
  = render "layouts/footer"

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %ol.microposts
    = render @feed_items
  = will_paginate @feed_items

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "新しい投稿をしましょう" %>
  </div>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
  <span class="picture">
   <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
 </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_user_info.html.haml
= link_to gravatar_for(current_user, size: 50), current_user
%h1= current_user.name
%span= link_to "自分のプロフィールを見る", current_user
%span= pluralize(current_user.microposts.count, "micropost")